// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYcbPmw3ZBx7wUNc7doeF1f_aEeMK6W40',
    appId: '1:193166714237:web:d4bbaeceb7143d279dd814',
    messagingSenderId: '193166714237',
    projectId: 'eat-soon-001',
    authDomain: 'eat-soon-001.firebaseapp.com',
    storageBucket: 'eat-soon-001.firebasestorage.app',
    measurementId: 'G-HFN00KHQW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzyGGG10mWptfMHF-e8PY6MbtcH4LP6A4',
    appId: '1:193166714237:android:210d8f731814c7999dd814',
    messagingSenderId: '193166714237',
    projectId: 'eat-soon-001',
    storageBucket: 'eat-soon-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9SGtpY6DEATPYuQfeSRBw2cNWQ97ZJOA',
    appId: '1:193166714237:ios:b32c6e1db32602ab9dd814',
    messagingSenderId: '193166714237',
    projectId: 'eat-soon-001',
    storageBucket: 'eat-soon-001.firebasestorage.app',
    iosBundleId: 'com.example.eatSoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9SGtpY6DEATPYuQfeSRBw2cNWQ97ZJOA',
    appId: '1:193166714237:ios:b32c6e1db32602ab9dd814',
    messagingSenderId: '193166714237',
    projectId: 'eat-soon-001',
    storageBucket: 'eat-soon-001.firebasestorage.app',
    iosBundleId: 'com.example.eatSoon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYcbPmw3ZBx7wUNc7doeF1f_aEeMK6W40',
    appId: '1:193166714237:web:7ba2a9d4429326f89dd814',
    messagingSenderId: '193166714237',
    projectId: 'eat-soon-001',
    authDomain: 'eat-soon-001.firebaseapp.com',
    storageBucket: 'eat-soon-001.firebasestorage.app',
    measurementId: 'G-TWKBZFK3YZ',
  );

}